# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52abe27cf74c2e852d44d978f62726b4d180d05b38a0b9f1596cbe91377e29f90059406a0457eb212818b7ae3929f932f9c41934c2552ecbccd58fcb9f1be7d9

test:
  secret_key_base: 223f9ac9d772723a7823fd4a19e519ebdc652fc077f8ce3077d8a1cd30cf39f9f0ba8e72ffa24d45f371fdee165cfe46527201381d447b2ff6c0ee4b1776bb60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
